### ISSUE TITLE
A tiny space below user area

### ISSUE THREAD

**Issue by vikoprez** [Synaelle/GitHub_Dark_Revival#6]
There is a 1px margin below user area caused by `margin-bottom: 1px` of `container-YkUktl` class that looks quite annoying for me XD
![image](https://user-images.githubusercontent.com/39916192/158214277-583009ce-c4f9-444b-9372-fed0a7a5dcb9.png)
Since it's not really important I would leave it to you to the next update of this amazing theme, thank you!

**Comment by Synaelle** [comment]
I can't unnotice that, I don't thank you (jk)
fixed
